"""
Django settings for trainee_subject project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_NAME = 'trainee_subject'

SITE_ID = 1
REVIEWER_SITE_ID = 40

# SITE_ID = 40
# REVIEWER_SITE_ID = 1

ETC_DIR = os.path.join(BASE_DIR, 'etc')
# AUTO_CREATE_KEYS=True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+p$o&4r71c1f84tri0xbbxag9i0cw1$&3_+mq(#=64&ly7sl^7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_crypto_fields.apps.AppConfig',
    'django_revision.apps.AppConfig',
    'edc_base.apps.AppConfig',
    'edc_device.apps.AppConfig',
    'edc_consent.apps.AppConfig',
    'edc_visit_schedule.apps.AppConfig',
    'trainee_subject.apps.AppConfig',
    'trainee_subject.apps.EdcAppointmentAppConfig',
    'trainee_subject.apps.EdcTimepointAppConfig',
    'trainee_subject.apps.EdcFacilityAppConfig',
    'trainee_subject.apps.EdcIdentifierAppConfig',
    'trainee_subject.apps.EdcMetadataAppConfig',
    'trainee_subject.apps.EdcProtocolAppConfig',
    'trainee_subject.apps.EdcVisitTrackingAppConfig',
    'trainee_subject.apps.EdcLabAppConfig',
    'edc_action_item.apps.AppConfig',
    'edc_locator.apps.AppConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'edc_dashboard.middleware.DashboardMiddleware',
    'edc_subject_dashboard.middleware.DashboardMiddleware',
]

ROOT_URLCONF = 'trainee_subject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trainee_subject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Gaborone'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_ROOT = os.path.join(BASE_DIR, 'trainee_subject', 'static')
STATIC_URL = '/static/'
# KEY_PATH = os.path.join(BASE_DIR, 'crypto_fields')
DEVICE_ID = '99'
EDC_LAB_REQUISITION_MODEL = 'trainee_subject.subjectrequisition'
DEVICE_ROLE = 'CentralServer'
GIT_DIR = BASE_DIR
COUNTRY = 'botswana'
HOLIDAY_FILE = os.path.join(BASE_DIR, APP_NAME, 'holidays.csv')


# KEY_PATH = os.path.join(BASE_DIR, 'crypto_fields')


DEFAULT_APPOINTMENT_MODEL = 'trainee_subject.appointment'

DASHBOARD_URL_NAMES = {
    'subject_listboard_url': 'trainee_dashboard:subject_listboard_url',
    'screening_listboard_url': 'trainee_dashboard:screening_listboard_url',
    'subject_dashboard_url': 'trainee_dashboard:subject_dashboard_url',
}

EDC_SYNC_SERVER_IP = None
EDC_SYNC_FILES_REMOTE_HOST = None
EDC_SYNC_FILES_USER = None
EDC_SYNC_FILES_USB_VOLUME = None

DASHBOARD_URL_NAMES = {
    'consent_listboard_url': 'trainee_dashboard:consent_listboard_url',
    'subject_listboard_url': 'trainee_dashboard:checklist_listboard_url',
    'subject_dashboard_url': 'trainee_dashboard:subject_dashboard_url',
}